// <auto-generated />
namespace WebApplication14.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _210820162217 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_210820162217));
        
        string IMigrationMetadata.Id
        {
            get { return "201608211913169_210820162217"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
