// <auto-generated />
namespace WebApplication14.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _23081601526 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_23081601526));
        
        string IMigrationMetadata.Id
        {
            get { return "201608231225349_23081601526"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
