// <auto-generated />
namespace WebApplication14.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _010920161125 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_010920161125));
        
        string IMigrationMetadata.Id
        {
            get { return "201609010825072_010920161125"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
